name: Deploy to VPS

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 50.184.90.90
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          command_timeout: 5m
          script: |
            cd /var/www/stayntour || cd ~/stayntour
            git fetch origin
            git reset --hard origin/main
            npm install
            npm test
            npm run build
            pm2 restart stayntour --update-env || pm2 start "npm run start" --name "stayntour"
            pm2 save
